### ISSUE TITLE
have an option to turn off benchmarks

### ISSUE THREAD

**Issue by ppelleti** [harendra-kumar/package-test#1]
It would be nice to have an option to turn off benchmarks.  I'm running into problems because my benchmarks use Criterion, and the latest version of Criterion doesn't build on Windows.  (And the previous version of Criterion doesn't support ghc 8.0.1, so I can't use that, either.)

I'd like to just be able to say I don't want to build the benchmarks or their dependencies, but it appears that STACK_DEP_OPTIONS is hardcoded to "--test --bench --only-dependencies --ghc-options=-O0" and there doesn't seem to be a way to override it.

**Comment by harendra-kumar** [comment]
How about a `DISABLE_BENCH` envvar to disable building benchmarks?

**Comment by harendra-kumar** [comment]
BTW, criterion builds successfully on 64-bit windows, so you can use the following in your appveyor.yml:

```
platform: x64
```

**Comment by ppelleti** [comment]
Thanks!  The option solved my problem!

Also, thanks for the tip about 64-bit.  I hadn't realized Appveyor was available in a 64-bit version.
